version: '3.8'
services:
    rabbitmq:
        image: rabbitmq:3.8-management
        networks:
            - app-network
        ports:
            - 5672:5672
            - 15672:15672
    #stock-service:
    #    image: deliverymuch/backend-challenge:stock-service
    #    networks:
    #        - app-network
    #    environment:
    #        - RABBITMQ_URL=amqp://rabbitmq
    #   depends_on:
    #        - rabbitmq
    #        - db
    #    links:
    #        - rabbitmq
    #        - db
    #    restart: on-failure
    db:
        image: mysql:8.0.17
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        ports:
            - '3306:3306'
        environment:
            - TZ=America/Sao_Paulo
            - MYSQL_ROOT_PASSWORD=backendchallenge
            - MYSQL_DATABASE=backendchallenge
            - MYSQL_USER=backendchallenge
            - MYSQL_PASSWORD=backendchallenge
networks:
    app-network:
        driver: bridge
