version: '3.0'
services:
    rabbitmq:
        image: rabbitmq:3.8-management
        networks:
            - app-network
        restart: on-failure
        ports:
            - 5672:5672
            - 15672:15672
    webapp:
        build: .
        command: ['yarn', 'start']
        #command: ['wait-for-it\wait-for-it.sh', 'rabbitmq:5672', '--', 'yarn', 'start']
        networks:
            - app-network
        env_file:
            - prod.env
        depends_on:
            - rabbitmq
            - mysql
            - migration
        links:
            - 'rabbitmq'
            - 'mysql'
        ports:
            - '3000:3000'
        restart: on-failure
    migration:
        image: backend-challenge_webapp:latest
        command: ['yarn', 'typeorm', 'migration:run']
        networks:
            - app-network
        env_file:
            - prod.env
        depends_on:
            - mysql
        links:
            - 'mysql'
        restart: on-failure
    mysql:
        image: mysql:8.0.17
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        networks:
            - app-network
        ports:
            - '3306:3306'
        environment:
            - TZ=America/Sao_Paulo
            - MYSQL_ROOT_PASSWORD=backendchallenge
            - MYSQL_DATABASE=backendchallenge
            - MYSQL_USER=backendchallenge
            - MYSQL_PASSWORD=backendchallenge
networks:
    app-network:
        driver: bridge
